name: Check style

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - main

jobs:
  Check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display repository name
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          Write-Host "The repository is: ${env:REPOSITORY}"

      - name: Install .NET 9
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'  # Use latest .NET 9 SDK

      - name: Add dotnet9 preview NuGet feed (necessary for InspectCode)
        run: dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json -n dotnet9

      - name: Install dotnet tools
        working-directory: src
        run: dotnet tool restore

      - name: Check format
        working-directory: src
        run: powershell .\CheckFormat.ps1

      - name: Build for inspection
        working-directory: src
        run: dotnet build -c DebugSlow

      - name: Inspect code
        working-directory: src
        run: powershell .\InspectCode.ps1
